from typing import TypedDict, Annotated, Sequence
import operator
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage, SystemMessage
from langgraph.graph import StateGraph, END
from langchain_google_genai import ChatGoogleGenerativeAI
import os
import re
from .github_utils import create_branch, commit_file, open_pull_request

# Define the State for LangGraph
class AgentState(TypedDict):
    messages: Annotated[Sequence[BaseMessage], operator.add]
    project_id: int
    sender: str
    channel: str # e.g. 'slack_123', 'discord_456'
    current_agent: str
    plan: str
    github_pr_url: str
    requires_approval: bool

def init_llm():
    return ChatGoogleGenerativeAI(
        model="gemini-1.5-flash", 
        temperature=0.2, 
        google_api_key=os.environ.get('GEMINI_API_KEY')
    )

def warden_node(state: AgentState):
    """The Warden checks for PII, secrets, and routes to the right agent."""
    from .memory_engine import retrieve_persona_context
    llm = init_llm()
    messages = state['messages']
    
    # Context Injection: Retrieve manager's style rules
    persona_rules = retrieve_persona_context(state['project_id'], str(messages[0].content))
    
    prompt = SystemMessage(content=f'''You are The Warden, the Security & Privacy Agent.
    1. Redact any obvious passwords, API keys, or PII from the user's message.
    2. Determine which agent should handle this request:
       - 'Data Engineer' if it involves DB schemas, SQL, or Neon/Postgres.
       - 'SRE/DevOps' if it involves CI/CD, GitHub Actions, or deployment.
       - 'Optimizer' if it is a log alert from #server-logs.
       - 'Architect' for all other system design or feature requests.
       
    MANAGER STYLE PROFILE (apply to the workflow): 
    {persona_rules}
    
    Output ONLY the name of the next agent.''')
    
    response = llm.invoke([prompt] + messages)
    next_agent = response.content.strip()
    
    # We will enforce routing in the conditional edge
    valid_agents = ['Data Engineer', 'SRE/DevOps', 'Optimizer', 'Architect']
    if next_agent not in valid_agents:
        next_agent = 'Architect'
        
    return {"current_agent": next_agent}

def architect_node(state: AgentState):
    llm = init_llm()
    messages = state['messages']
    prompt = SystemMessage(content="You are The Architect. Design the tech stack logic and infrastructure plans based on the user request. Draft a cohesive markdown plan.")
    response = llm.invoke([prompt] + messages)
    return {"messages": [response], "plan": response.content}

def extract_code_block(content):
    match = re.search(r'```(?:\w+\n)?(.*?)```', content, re.DOTALL)
    if match:
        return match.group(1).strip()
    return content.strip()

def data_engineer_node(state: AgentState):
    llm = init_llm()
    messages = state['messages']
    prompt = SystemMessage(content="You are Data Engineer Agent. Write raw SQL or Django ORM models. Output ONLY the code block containing the model or SQL.")
    response = llm.invoke([prompt] + messages)
    
    # GitOps Action: Commit generated model code
    repo = os.environ.get('TARGET_GITHUB_REPO', 'yourusername/target-repo')
    branch = create_branch(repo, "feat/data-models")
    code_content = extract_code_block(response.content)
    commit_file(repo, branch, "models.py", code_content, "Data Engineer: Added new models")
    
    pr_url = open_pull_request(repo, branch, "Data Models Update", "Generated by Data Engineer Agent via DevOps Copilot.")
    
    pr_msg = AIMessage(content=f"I have created the requested data models and opened a Pull Request for your review: {pr_url}")
    return {"messages": [pr_msg], "github_pr_url": pr_url, "requires_approval": True}

def sre_node(state: AgentState):
    llm = init_llm()
    messages = state['messages']
    prompt = SystemMessage(content="You are SRE/DevOps Agent. Write GitHub Actions CI/CD YAML scripts. Output ONLY the YAML codeblock.")
    response = llm.invoke([prompt] + messages)
    
    # GitOps Action: Commit CI/CD script
    repo = os.environ.get('TARGET_GITHUB_REPO', 'yourusername/target-repo')
    branch = create_branch(repo, "chore/cicd-pipeline")
    yaml_content = extract_code_block(response.content)
    commit_file(repo, branch, ".github/workflows/deploy.yml", yaml_content, "SRE Agent: Updated deployment pipeline")
    
    pr_url = open_pull_request(repo, branch, "CI/CD Pipeline Update", "Generated by SRE Agent via DevOps Copilot.")
    
    pr_msg = AIMessage(content=f"I have configured the deployment actions and opened a PR: {pr_url}")
    return {"messages": [pr_msg], "github_pr_url": pr_url, "requires_approval": True}

def optimizer_node(state: AgentState):
    llm = init_llm()
    messages = state['messages']
    prompt = SystemMessage(content="You are the Optimizer Agent. Analyze the error logs. Output the code fix necessary.")
    response = llm.invoke([prompt] + messages)
    
    # Auto-Remediation PR
    repo = os.environ.get('TARGET_GITHUB_REPO', 'yourusername/target-repo')
    branch = create_branch(repo, "fix/auto-remediation")
    fixed_code = extract_code_block(response.content)
    commit_file(repo, branch, "fixed_file.py", fixed_code, "Optimizer Agent: Auto-remediation formatting/logic fix")
    
    pr_url = open_pull_request(repo, branch, "Auto-Remediation Formatter Fix", "Generated by Optimizer Agent via DevOps Copilot based on log analysis.")
    
    pr_msg = AIMessage(content=f"I analyzed the logs and created an auto-remediation PR for your approval: {pr_url}")
    return {"messages": [pr_msg], "github_pr_url": pr_url, "requires_approval": True}

# Routing function
def route_after_warden(state: AgentState):
    current = state.get("current_agent")
    if current == 'Data Engineer':
        return 'data_engineer'
    elif current == 'SRE/DevOps':
        return 'sre'
    elif current == 'Optimizer':
        return 'optimizer'
    return 'architect'

def build_graph():
    workflow = StateGraph(AgentState)
    
    workflow.add_node("warden", warden_node)
    workflow.add_node("architect", architect_node)
    workflow.add_node("data_engineer", data_engineer_node)
    workflow.add_node("sre", sre_node)
    workflow.add_node("optimizer", optimizer_node)
    
    workflow.set_entry_point("warden")
    
    workflow.add_conditional_edges("warden", route_after_warden, {
        "data_engineer": "data_engineer",
        "sre": "sre",
        "optimizer": "optimizer",
        "architect": "architect"
    })
    
    workflow.add_edge("architect", END)
    workflow.add_edge("data_engineer", END)
    workflow.add_edge("sre", END)
    workflow.add_edge("optimizer", END)
    
    return workflow.compile()

# Dependency injection for the SQS consumer
def invoke_swarm(initial_message: str):
    app = build_graph()
    state = {
        "messages": [HumanMessage(content=initial_message)],
        "project_id": 1, 
        "sender": "webhook",
        "channel": "slack/discord"
    }
    
    result = app.invoke(state)
    return result['messages'][-1].content
